server:
  port: 8899
  contextPath: /userauth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka/	  
	  
security:
  user:
    password: password

logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: admin
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create